#!/bin/sh
# Case: v1.1.4 byte-identical regression contract.
#
# Asserts that modulejail v1.2 with --no-syslog-logging, run against the
# archived v1.1.4-era canned inputs (proc-modules + modules-list + pinned
# kver), produces output whose BODY is byte-identical to the archived
# expected-blacklist.conf generated by v1.1.4 against the same inputs.
#
# Body-only: three header lines legitimately changed between v1.1.4 and v1.2
# and are filtered out before the diff:
#   # modulejail <version>      - VERSION line bumped 1.1.4 -> 1.2.0
#   # fingerprint: sha256:...    - filtered defensively; on identical inputs
#                                  the fingerprint IS identical, but if a
#                                  future version touches the fingerprint
#                                  inputs the body-diff stays clean
#   # install-line: ...          - new in v1.2, absent in v1.1.4
# All other lines (kernel, profile, disclaimer, every install line) MUST
# match exactly.
#
# The fixture's universe is rebuilt from tests/fixtures/v1.1.4-regression/
# modules-list (6474 basenames). The case builds a synthetic /lib/modules/
# tree of empty files matching those basenames under $CASE_TMP and points
# modulejail at it via MODULEJAIL_MODULES_ROOT (test-only plumbing). The
# fixture's proc-modules and kver pin the loaded set and kernel version.
# Net effect: the case is hermetic, network-free, and runs on any host
# that can execute /bin/sh - including the macOS dev box.
set -eu

CASE_NAME=v1.1.4-regression
export CASE_NAME

# Locate repo root and fixture dir relative to this script (so the case
# runs from any cwd, including via tests/run-fixtures.sh --filter).
case "${0:-}" in
    /*) CASE_SCRIPT=$0 ;;
    *)  CASE_SCRIPT=$(pwd)/$0 ;;
esac
CASE_DIR=$(cd "$(dirname "$CASE_SCRIPT")" && pwd)
REPO_ROOT=$(cd "$CASE_DIR/../.." && pwd)
MODULEJAIL_BIN=$REPO_ROOT/modulejail
FIXTURE_DIR=$REPO_ROOT/tests/fixtures/v1.1.4-regression

# Sanity-check the fixture is present.
for f in proc-modules kver modules-list expected-blacklist.conf; do
    if [ ! -f "$FIXTURE_DIR/$f" ]; then
        printf '[%s] FAIL: missing fixture file: %s\n' "$CASE_NAME" "$FIXTURE_DIR/$f" >&2
        exit 1
    fi
done

CASE_TMP=$(mktemp -d "${TMPDIR:-/tmp}/modulejail-v114-regression.XXXXXX")
trap 'rm -rf "$CASE_TMP"' EXIT INT HUP TERM

# Rebuild the synthetic modules tree from the canned list. All 6474
# entries in the v1.1.4 fixture use .ko.zst; the list is shipped as-is
# (basename per line). The script's list_universe walks recursively via
# `find -type f -name '*.ko*'` and only uses the basename, so the
# directory layout does not matter for the regression contract.
#
# 2-tier sharding (lo/ + uc/) is REQUIRED to survive case-insensitive
# filesystems (default macOS APFS). The v1.1.4 fixture's modules-list
# contains four uppercase-vs-lowercase basename pairs (xt_DSCP / xt_dscp,
# xt_HL / xt_hl, xt_RATEEST / xt_rateest, xt_TCPMSS / xt_tcpmss); on
# Linux ext4/xfs these are distinct inodes, but on a single flat
# case-insensitive dir the second touch updates the first's mtime
# instead of creating a sibling, silently dropping four modules from the
# synthetic universe. Sharding files-with-any-uppercase into uc/ and
# all-lowercase into lo/ gives the two case-variant groups separate
# basename namespaces, so they coexist on APFS as well as on ext4.
KVER=$(cat "$FIXTURE_DIR/kver")
TREE_ROOT=$CASE_TMP/lib/modules/$KVER
mkdir -p "$TREE_ROOT/lo" "$TREE_ROOT/uc"
# awk classifies each line (has-any-uppercase vs all-lowercase) and
# routes to uc/ or lo/. Then a single batched xargs invocation does the
# touches.
awk '{
    has_upper = 0
    for (i=1; i<=length($0); i++) {
        c = substr($0, i, 1)
        if (c >= "A" && c <= "Z") { has_upper = 1; break }
    }
    if (has_upper) print "uc/" $0
    else           print "lo/" $0
}' "$FIXTURE_DIR/modules-list" > "$CASE_TMP/manifest"
(cd "$TREE_ROOT" && xargs touch < "$CASE_TMP/manifest")

# Generate the v1.2 candidate output with --no-syslog-logging set so the
# install-line body matches the v1.1.4 form (byte-identical contract).
ACTUAL=$CASE_TMP/actual.conf
MODULEJAIL_MODULES_ROOT=$CASE_TMP/lib/modules \
MODULEJAIL_KVER=$KVER \
MODULEJAIL_PROC_MODULES=$FIXTURE_DIR/proc-modules \
MODULEJAIL_NO_UPDATE_CHECK=1 \
MODULEJAIL_DEFAULT_WHITELIST_FILE=$CASE_TMP/default-whitelist-absent.conf \
"$MODULEJAIL_BIN" -p conservative --no-syslog-logging -o "$ACTUAL" > "$CASE_TMP/stdout" 2> "$CASE_TMP/stderr" || {
    rc=$?
    printf '[%s] FAIL: modulejail exited %d (expected 0); stderr=%s\n' \
        "$CASE_NAME" "$rc" "$(cat "$CASE_TMP/stderr")" >&2
    exit 1
}

# Body-only diff: drop the three legitimately-changed header lines.
# All other lines (kernel, profile, disclaimer, every install line) must
# match the archived v1.1.4 reference.
EXPECTED_FILTERED=$CASE_TMP/expected.body
ACTUAL_FILTERED=$CASE_TMP/actual.body
grep -v -E '^# modulejail |^# fingerprint:|^# install-line:|^# invocation:' \
    "$FIXTURE_DIR/expected-blacklist.conf" > "$EXPECTED_FILTERED"
grep -v -E '^# modulejail |^# fingerprint:|^# install-line:|^# invocation:' \
    "$ACTUAL" > "$ACTUAL_FILTERED"

if ! diff -u "$EXPECTED_FILTERED" "$ACTUAL_FILTERED" > "$CASE_TMP/diff.out"; then
    printf '[%s] FAIL: v1.1.4 regression body diverged from reference:\n' "$CASE_NAME" >&2
    head -40 "$CASE_TMP/diff.out" >&2
    exit 1
fi

# Sanity: the expected counts (6363 of 6474) ARE the v1.1.4 reference
# counts.  Confirm v1.2 head produced the same totals (this would also
# fall out of a body-identical diff above, but the explicit check makes
# the regression contract self-documenting in test output).
EXPECTED_COUNT=$(grep -c '^install ' "$FIXTURE_DIR/expected-blacklist.conf")
ACTUAL_COUNT=$(grep -c '^install ' "$ACTUAL")
if [ "$EXPECTED_COUNT" != "$ACTUAL_COUNT" ]; then
    printf '[%s] FAIL: install-line count drift: expected %d got %d\n' \
        "$CASE_NAME" "$EXPECTED_COUNT" "$ACTUAL_COUNT" >&2
    exit 1
fi

printf '[%s] PASS (%d/%d install lines body-identical to v1.1.4 reference)\n' \
    "$CASE_NAME" "$ACTUAL_COUNT" "$EXPECTED_COUNT"
exit 0
